openapi: 3.0.0
info:
  title: Summarize an article API
  version: 1.0.0
  description: APIs for summarize an article from URL.
paths:
  /summarize_article:
    post:
      summary: APIs for summarize an article from URL.
      description: The URL should be determined based on the instructions.
      operationId: summarize
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: url of article
              required:
              - url
      responses:
        '200':
          description: Article summarized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    type: string
                    description: Summarized article